Fix Python 3.14 compatibility of quantization/pt2e (#4427)
Avoids the error:
```
AttributeError: 'typing.Union' object has no attribute '__module__'
```

This is a known issue, in Python 3.14 it's no longer supported to
do this.

Closes gh-3619
Supersedes and closes gh-3657