Fix test_sparse_api failures for builds without hipSPARSELt (#4125) (#4125)
Summary:

What: Add a guard in test/sparsity/test_sparse_api.py so tests that depend on `hipSPARSELt` only run when the backend is available.

Why: These tests currently fail on environments without hipSPARSELt, for example OSS AO nightly. Since the functionality is environment dependent, these test should be conditionally skipped. https://fburl.com/9fpszdqg

```
FAILED test/sparsity/test_sparse_api.py::TestSemiStructuredSparse::test_sparse - RuntimeError: hipSPARSELt not supported on your machine.
```

Differential Revision: D97540060