Fix torch.intx support in FakeQuantizeConfig (#1544)
**Summary:** Fixes the following error when passing `torch.intx` to
`FakeQuantizeConfig`. These dtypes were introduced in PyTorch 2.6+:

```
ValueError: Unsupported dtype 'torch.int4', choose from [torch.int8, torch.uint8, <TorchAODType.INT1: 1>, <TorchAODType.INT2: 2>, <TorchAODType.INT3: 3>, <TorchAODType.INT4: 4>, <TorchAODType.INT5: 5>, <TorchAODType.INT6: 6>, <TorchAODType.INT7: 7>, torch.uint1, torch.uint2, torch.uint3, torch.uint4, torch.uint5, torch.uint6, torch.uint7]
```

**Test Plan:**
python test/quantization/test_qat.py -k test_fake_quantize_config_torch_intx