Adding test with real op implementation
the new test with real op fails for the same line
self.assertIsNot(Parent._ATEN_OP_TABLE, Child._ATEN_OP_TABLE).

Also when it is called using the child tensor, it works.

For the inheritance test case,
it fails at
self.assertEqual(C._ATEN_OP_TABLE[C]["shared"], "from_b")
AssertionError: 'from_a' != 'from_b'