Fix static AQT flow (#2046)
**Summary:** Fixes this error with the static AQT flow:
```
  File "/home/andrewor/local/ao/test/dtypes/test_affine_quantized.py", line 269, in test_to_affine_quantized_intx_static
    to_affine_quantized_intx_static(
  File "/home/andrewor/local/ao/torchao/dtypes/affine_quantized_tensor.py", line 325, in from_hp_to_intx_static
    input_float, scale, zero_point = _layout.pre_process_static(
TypeError: Layout.pre_process_static() missing 1 required positional argument: 'block_size'
```

**Test Plan:**
python test/dtypes/test_affine_quantized.py -k test_to_affine_quantized_intx_static
python tutorials/calibration_flow/static_quant.py