Support NVFP4 fp32 bias (#3525)
**Summary:** Today we hit this error with fp32 inputs + bias:

```
RuntimeError: Bias is not supported when module weight is in fp32
(out_dtype=Float32). Please use bfloat16 or float16 weights,
or remove the bias from the linear layer.
```

This is thrown by `NVFP4DynamicActivationNVFP4WeightConfig` but
it's trying to guard against this underlying `_scaled_mm` error:

```
RuntimeError: Bias is not supported when out_dtype is set to Float32
```

This commit works around these errors by adding the bias separately
in this case, similar to what float8 does.

**Test Plan:**

```
pytest test/prototype/mx_formats/test_inference_workflow.py -k test_inference_workflow_nvfp4
```