error on H100
Summary:

sh benchmarks.sh
Using device=cuda
Loading model ...
Time to load model: 2.36 seconds
quant mode:  gemsub-4-64
/home/cdhernandez/.conda/envs/pytorch-3.10/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
> /data/users/cdhernandez/ao/torchao/_models/llama/generate.py(512)main()
-> print("huh")
(Pdb) q
Traceback (most recent call last):
  File "/data/users/cdhernandez/ao/torchao/_models/llama/generate.py", line 509, in main
    print(tokenizer.decode(tokens))
  File "/data/users/cdhernandez/ao/torchao/_models/llama/tokenizer.py", line 35, in decode
    return self.processor.DecodeIds(tokens)
  File "/home/cdhernandez/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 876, in DecodeIds
    return self.Decode(input=input, out_type=out_type, **kwargs)
  File "/home/cdhernandez/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 801, in Decode
    return self._DecodeIds(input)
  File "/home/cdhernandez/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 343, in _DecodeIds
    return _sentencepiece.SentencePieceProcessor__DecodeIds(self, ids)
IndexError: Out of range: piece id is out of range.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags: